# Simple controller configuration for Gazebo simulation
controller_manager:
  ros__parameters:
    use_sim_time: true
    update_rate: 50

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    mecanum_drive_controller:
      type: mecanum_drive_controller/MecanumDriveController

mecanum_drive_controller:
  ros__parameters:
    use_sim_time: true

    # Joint names
    front_left_joint_name: front_left_wheel_joint
    front_right_joint_name: front_right_wheel_joint
    back_left_joint_name: back_left_wheel_joint
    back_right_joint_name: back_right_wheel_joint

    # Robot physical parameters
    wheel_base: 0.16
    wheel_separation: 0.169
    wheel_radius: 0.0325

    # TF configuration
    odom_frame_id: odom
    base_frame_id: base_footprint
    enable_odom_tf: true

    # Velocity limits
    linear:
      x:
        has_velocity_limits: true
        max_velocity: 1.0
        min_velocity: -1.0

    angular:
      z:
        has_velocity_limits: true
        max_velocity: 2.0
        min_velocity: -2.0

joint_state_broadcaster:
  ros__parameters:
    use_sim_time: true