<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename = "inertial_macros.xacro" />

    <xacro:property name="chassis_length"           value="0.320"/>
    <xacro:property name="chassis_width"            value="0.240"/>
    <xacro:property name="chassis_height"           value="0.078"/>
    <xacro:property name="chassis_mass"             value="0.700"/>

    <xacro:property name="wheel_radius"             value="0.034"/>
    <xacro:property name="wheel_thickness"          value="0.026"/>
    <xacro:property name="wheel_mass"               value="0.050"/>
    <xacro:property name="wheel_offset_x"           value="0.133"/>
    <xacro:property name="wheel_offset_y"           value="0.133"/>
    <xacro:property name="wheel_offset_z"           value="0.020"/>

    <xacro:property name="caster_wheel_radius"      value="${wheel_radius - wheel_offset_z}"/>
    <xacro:property name="caster_wheel_mass"        value="0.010"/>
    <xacro:property name="caster_wheel_offset_x"    value="0.230"/>
    <xacro:property name="caster_wheel_offset_z"    value="${wheel_offset_z - wheel_radius + caster_wheel_radius}"/>


    <!-- Colors -->
    <material name="white">
        <color rgba= "1 1 1 1"/>
    </material>

    <material name="black">
        <color rgba= "0 0 0 1"/>
    </material>

    <material name= "orange">
        <color rgba= "1 0.25 0 1"/>
    </material>

    <material name="cyan">
        <color rgba= "0 1 1 1"/>
    </material>

    <material name="indigo">
        <color rgba= "0.294 0 0.51 1"/>
    </material>


    <!-- convention (except base_link): joint followed by link -->
    <!-- base_link -->
    <link name="base_link">
    </link>

    <!-- base_footprint -->
    <joint name="base_footprint_joint" type="fixed">
        <parent link= "base_link"/>
        <child link= "base_footprint"/>
        <origin xyz= "0 0 0" rpy= "0 0 0"/>
    </joint>

    <link name="base_footprint">
    </link>

    <!-- chasis -->
    <joint name="chasis_joint" type="fixed">
        <parent link= "base_link"/>
        <child link= "chasis"/>
        <origin xyz= "${-wheel_offset_x} 0 ${-wheel_offset_z}"/>
    </joint>

    <link name="chasis">
        <visual>
            <origin xyz= "${chassis_length/2} 0 ${chassis_height/2}" rpy= "0 0 0"/>
            <geometry>
                <box size = "${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
            <material name= "black"/>
        </visual>
        <collision>
            <origin xyz= "${chassis_length/2} 0 ${chassis_height/2}" rpy= "0 0 0"/>
            <geometry>
                <box size = "${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass= "0.5" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}">
            <origin xyz= "${chassis_length/2} 0 ${chassis_height/2}" rpy= "0 0 0"/>
        </xacro:inertial_box>
    </link>

    <gazebo reference="chasis">
        <material>Gazebo/Black</material>
    </gazebo>

    <!-- left_wheel -->
    <joint name="left_wheel_joint" type="continuous">
        <parent link= "base_link"/>
        <child link= "left_wheel"/>
        <origin xyz= "0 ${wheel_offset_y} 0" rpy = "${pi/2} 0 0"/>
        <axis xyz= "0 0 -1"/>
    </joint>

    <link name="left_wheel">
        <visual>
            <geometry>
                <cylinder radius = "${wheel_radius}" length= "${wheel_thickness}"/>
            </geometry>
            <material name= "orange"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius = "${wheel_radius}" />
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass = "${wheel_mass}" radius= "${wheel_radius}" length= "${wheel_thickness}">
            <origin xyz= "0 0 0" rpy= "0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="left_wheel">
        <material>Gazebo/Orange</material>
    </gazebo>

    <!-- right_wheel -->
    <joint name="right_wheel_joint" type="continuous">
        <parent link= "base_link"/>
        <child link= "right_wheel"/>
        <origin xyz= "0 ${-wheel_offset_y} 0" rpy = "${pi/2} 0 0"/>
        <axis xyz= "0 0 -1"/>
    </joint>

    <link name="right_wheel">
        <visual>
            <geometry>
                <cylinder radius = "${wheel_radius}" length= "${wheel_thickness}"/>
            </geometry>
            <material name= "orange"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius = "${wheel_radius}" />
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass = "${wheel_mass}" radius= "${wheel_radius}" length= "${wheel_thickness}">
            <origin xyz= "0 0 0" rpy= "0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="right_wheel">
        <material>Gazebo/Orange</material>
    </gazebo>

    <!-- caster_wheel -->
    <joint name="caster_wheel_joint" type="fixed">
        <parent link= "chasis"/>
        <child link= "caster_wheel"/>
        <origin xyz= "${caster_wheel_offset_x} 0 0"/>
    </joint>

    <link name="caster_wheel">
        <visual>
            <geometry>
                <sphere radius = "${caster_wheel_radius}"/>
            </geometry>
            <material name= "orange"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius = "${caster_wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_sphere mass= "${caster_wheel_mass}" radius= "${caster_wheel_radius}">
            <origin xyz= "0 0 0" rpy= "0 0 0"/>
        </xacro:inertial_sphere>
    </link>

    <gazebo reference="caster_wheel">
        <material>Gazebo/Orange</material>
        <mu1 value= "0.0001"/>
        <mu2 value= "0.0001"/>
    </gazebo>


</robot>